# General Settings
name: Behrang
job_title: Programmer
email: behrangsa@gmail.com
description: "things.forEach(t -> t.do())"
avatar: /assets/images/avatar-2.jpeg
favicon: /favicon.ico
twitter_handler: behrangsa
# analytics_code: UA-XXXXXXX-2
# disqus: your_disqus_site

# Social Accounts
social_networks:
-  { name: linkedin, url: 'https://www.linkedin.com/in/behrangsa' }
-  { name: github, url: 'https://github.com/behrangsa/' }
-  { name: stack-overflow, url: 'http://stackoverflow.com/users/309683/behrang' }
-  { name: twitter, url: 'https://twitter.com/behrangsa' }

# -  { name: codepen, url: 'http://codepen.io/behrangsa/' }
# -  { name: vimeo, url: '' }
# -  { name: flickr, url: '' }
# -  { name: spotify, url: '' }
# -  { name: instagram, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 0
show_rss: 0
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "https://behrangsa.github.io"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed